name: aju_machine_test
description: A new Flutter application.
publish_to: 'none' #
version: 3.5.0+35

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.1
  shared_preferences: ^2.0.11
  connectivity: ^3.0.6
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.0
  firebase_messaging_platform_interface: 3.1.6
  flutter_local_notifications: ^9.1.4
  path_provider: ^2.0.8
  url_strategy: ^0.2.0
  pin_code_fields: ^7.3.0
  geolocator: ^8.0.1
  google_maps_flutter: ^2.1.1
  google_maps_flutter_web: ^0.3.2
  shimmer_animation: ^2.1.0+1
  universal_ui: ^0.0.8
  webview_flutter: ^3.0.0
  flutter_widget_from_html_core: ^0.8.4
  url_launcher: ^6.0.17
  http: ^0.13.4
  pointer_interceptor: ^0.9.0+1
  phone_number: ^0.12.0+1
  country_code_picker: ^2.0.2
  cached_network_image: ^3.2.0
  google_sign_in: ^5.2.1
  http_multi_server: ^2.2.0
  fvm: ^2.2.6
  firebase_auth: ^2.0.0
  # firebase_phone_auth_handler: ^1.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900